
Model：
-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:    	2023-04-10 01:27:30 EDT
--   site:  	Oracle Database 11g
--   type:  	Oracle Database 11g
 
 
 
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
 
-- predefined type, no DDL - XMLTYPE
 
CREATE TABLE category (
	category_id   NUMBER(8) NOT NULL,
	category_type VARCHAR2(20)
);
 
ALTER TABLE category ADD CONSTRAINT category_pk PRIMARY KEY ( category_id );
 
CREATE TABLE customer (
	customer_id	NUMBER(8) NOT NULL,
	customer_name  VARCHAR2(20) NOT NULL,
	customer_phone NUMBER(10) NOT NULL,
	customer_email VARCHAR2(20) NOT NULL
);
 
ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );
 
CREATE TABLE employee (
	employee_id          	NUMBER(4) NOT NULL,
	employee_name        	VARCHAR2(30) NOT NULL,
	employee_phone       	NUMBER(10) NOT NULL,
	employee_address     	VARCHAR2(50),
	employee_email       	VARCHAR2(30),
	restaurant_restaurant_id NUMBER(8)
);
 
ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );
 
CREATE TABLE "Order" (
	order_id 	NUMBER(8) NOT NULL,
	reorder_info VARCHAR2(20)
);
 
ALTER TABLE "Order" ADD CONSTRAINT order_pk PRIMARY KEY ( order_id );
 
CREATE TABLE order_address (
	order_address_id NUMBER(8) NOT NULL,
	o_state      	VARCHAR2(20) NOT NULL,
	o_city       	VARCHAR2(20),
	o_zip_code   	VARCHAR2(20)
);
 
ALTER TABLE order_address ADD CONSTRAINT order_address_pk PRIMARY KEY ( order_address_id );
 
CREATE TABLE order_fact (
	order_fact_id              	NUMBER(8) NOT NULL,
	time_id                    	NUMBER(8) NOT NULL,
	product_id                 	NUMBER(8) NOT NULL,
	order_order_id             	NUMBER(8) NOT NULL,
	customer_customer_id       	NUMBER(8) NOT NULL,
	order_address_order_address_id NUMBER(8) NOT NULL
);
 
ALTER TABLE order_fact ADD CONSTRAINT order_fact_pk PRIMARY KEY ( order_fact_id );
 
CREATE TABLE product (
	product_id   NUMBER(8) NOT NULL,
	product_name VARCHAR2(20) NOT NULL
);
 
ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( product_id );
 
CREATE TABLE restaurant (
	restaurant_id 	NUMBER(8) NOT NULL,
	restaurant_name   VARCHAR2(30) NOT NULL,
	restaurant_rating FLOAT(2) NOT NULL
);
 
ALTER TABLE restaurant ADD CONSTRAINT restaurant_pk PRIMARY KEY ( restaurant_id );
 
CREATE TABLE restaurant_business_time (
	restaurant_business_time_id NUMBER(8) NOT NULL,
	open_time      	         VARCHAR2(10) NOT NULL,
	close_time              	VARCHAR2(10) NOT NULL
);
 
ALTER TABLE restaurant_business_time ADD CONSTRAINT restaurant_business_time_pk PRIMARY KEY ( restaurant_business_time_id );
 
CREATE TABLE resturant_address (
	rest_address_id NUMBER(8) NOT NULL,
	o_state     	VARCHAR2(20) NOT NULL,
	o_city      	VARCHAR2(20),
	o_zip_code  	NUMBER(5)
);
 
ALTER TABLE resturant_address ADD CONSTRAINT resturant_address_pk PRIMARY KEY ( rest_address_id );
 
CREATE TABLE resturant_fact (
	rest_fact_id       	NUMBER(8) NOT NULL,
	category_id        	NUMBER(8) NOT NULL,
	resturant_address_id   NUMBER(8) NOT NULL,
	restaurant_bus_time_id NUMBER(8) NOT NULL,
	time_id        	    NUMBER(8) NOT NULL,
	product_id         	NUMBER(8) NOT NULL,
	restaurant_id      	NUMBER(8) NOT NULL
);
 
ALTER TABLE resturant_fact ADD CONSTRAINT resturant_fact_pk PRIMARY KEY ( rest_fact_id );
 
CREATE TABLE time (
	time_id 	NUMBER(8) NOT NULL,
	oder_year   VARCHAR2(10) NOT NULL,
	order_month VARCHAR2(10) NOT NULL,
	order_day   VARCHAR2(6) NOT NULL,
	order_hour  NUMBER(2) NOT NULL,
	order_min   NUMBER(2)
);
 
ALTER TABLE time ADD CONSTRAINT time_pk PRIMARY KEY ( time_id );
 
ALTER TABLE employee
	ADD CONSTRAINT employee_restaurant_fk FOREIGN KEY ( restaurant_restaurant_id )
    	REFERENCES restaurant ( restaurant_id );
 
ALTER TABLE order_fact
	ADD CONSTRAINT order_fact_customer_fk FOREIGN KEY ( customer_customer_id )
    	REFERENCES customer ( customer_id );
 
ALTER TABLE order_fact
	ADD CONSTRAINT order_fact_order_address_fk FOREIGN KEY ( order_address_order_address_id )
    	REFERENCES order_address ( order_address_id );
 
ALTER TABLE order_fact
	ADD CONSTRAINT order_fact_order_fk FOREIGN KEY ( order_order_id )
    	REFERENCES "Order" ( order_id );
 
ALTER TABLE order_fact
	ADD CONSTRAINT order_fact_product_fk FOREIGN KEY ( product_id )
    	REFERENCES product ( product_id );
 
ALTER TABLE order_fact
	ADD CONSTRAINT order_fact_time_fk FOREIGN KEY ( time_id )
    	REFERENCES time ( time_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT rest_fact_rest_address_fk FOREIGN KEY ( resturant_address_id )
    	REFERENCES resturant_address ( rest_address_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT resturant_fact_category_fk FOREIGN KEY ( category_id )
    	REFERENCES category ( category_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT resturant_fact_fk FOREIGN KEY ( restaurant_id )
    	REFERENCES restaurant ( restaurant_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT resturant_fact_product_fk FOREIGN KEY ( product_id )
    	REFERENCES product ( product_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT resturant_fact_time_fk FOREIGN KEY ( time_id )
    	REFERENCES time ( time_id );
 
ALTER TABLE resturant_fact
	ADD CONSTRAINT resturant_fact_time_fkv1 FOREIGN KEY ( restaurant_bus_time_id )
    	REFERENCES restaurant_business_time ( restaurant_business_time_id );
 
 
 
-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                        	12
-- CREATE INDEX                       	  0
-- ALTER TABLE                         	24
-- CREATE VIEW                          	0
-- ALTER VIEW                           	0
-- CREATE PACKAGE                       	0
-- CREATE PACKAGE BODY                  	0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                      	0
-- CREATE TRIGGER                       	0
-- ALTER TRIGGER                        	0
-- CREATE COLLECTION TYPE               	0
-- CREATE STRUCTURED TYPE               	0
-- CREATE STRUCTURED TYPE BODY          	0
-- CREATE CLUSTER                       	0
-- CREATE CONTEXT                       	0
-- CREATE DATABASE                      	0
-- CREATE DIMENSION                     	0
-- CREATE DIRECTORY     	                0
-- CREATE DISK GROUP                    	0
-- CREATE ROLE                          	0
-- CREATE ROLLBACK SEGMENT              	0
-- CREATE SEQUENCE                      	0
-- CREATE MATERIALIZED VIEW             	0
-- CREATE MATERIALIZED VIEW LOG         	0
-- CREATE SYNONYM                       	0
-- CREATE TABLESPACE                    	0
-- CREATE USER                          	0
--
-- DROP TABLESPACE                      	0
-- DROP DATABASE         	               0
--
-- REDACTION POLICY                     	0
--
-- ORDS DROP SCHEMA                     	0
-- ORDS ENABLE SCHEMA                   	0
-- ORDS ENABLE OBJECT                   	0
--
-- ERRORS                              	 0
-- WARNINGS                             	0



